# Generated by Django 6.0.5 on 2026-05-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("expire_le", models.DateTimeField()),
                ("utilise", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Vérification",
                "verbose_name_plural": "Vérifications",
            },
        ),
        migrations.AlterField(
            model_name="filiere",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="nom",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to="core.filiere",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="nom",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="nom",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("annee_academique", models.CharField(max_length=9)),
                ("fichier_pdf", models.FileField(upload_to="sujets/")),
                ("taille_pdf", models.CharField(blank=True, max_length=10, null=True)),
                ("auteur_nom", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("archive", "Archivé")],
                        default="actif",
                        max_length=10,
                    ),
                ),
                (
                    "visibilite",
                    models.CharField(
                        choices=[("visible", "Visible"), ("restreint", "Restreint")],
                        default="visible",
                        max_length=10,
                    ),
                ),
                ("date_publication", models.DateField(auto_now_add=True)),
                ("vues", models.IntegerField(default=0)),
                ("telechargements", models.IntegerField(default=0)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sujets",
                        to="core.filiere",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sujets",
                        to="core.matiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sujets",
                        to="core.niveau",
                    ),
                ),
                (
                    "publie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sujets_publies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sujet",
                "verbose_name_plural": "Sujets",
            },
        ),
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("telechargement", "Téléchargement"),
                            ("consultation", "Consultation"),
                            ("profil_modifie", "Profil modifié"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sujet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to="core.sujet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Telechargement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telecharge_le", models.DateTimeField(auto_now_add=True)),
                (
                    "sujet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telechargements_sujet",
                        to="core.sujet",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telechargements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Téléchargement",
                "verbose_name_plural": "Téléchargements",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("etudiant", "Étudiant"), ("admin", "Administrateur")],
                        default="etudiant",
                        max_length=10,
                    ),
                ),
                ("email_verifie", models.BooleanField(default=False)),
                ("avatar", models.URLField(blank=True, null=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etudiants",
                        to="core.filiere",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etudiants",
                        to="core.niveau",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
    ]
