# Generated by Django 6.0.5 on 2026-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ajout_ordre_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='tentatives',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
