# Generated by Django 6.0.5 on 2026-05-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_verification_tentatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiere",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
