# Generated by Django 5.2.14 on 2026-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_filiere_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="usage",
            field=models.CharField(
                choices=[
                    ("email", "Vérification email"),
                    ("password_reset", "Réinitialisation du mot de passe"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
