# Generated by Django 6.0.5 on 2026-06-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_verification_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='empreinte',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Empreinte SHA256 du fichier'),
        ),
    ]
