# Generated by Django 5.2.14 on 2026-06-02 12:45

import core.utils
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def deduplicate_catalog_and_push(apps, schema_editor):
    """Fusionne les doublons historiques avant la pose des contraintes."""
    Matiere = apps.get_model("core", "Matiere")
    Niveau = apps.get_model("core", "Niveau")
    PushSubscription = apps.get_model("core", "PushSubscription")
    Sujet = apps.get_model("core", "Sujet")
    Utilisateur = apps.get_model("core", "Utilisateur")

    niveaux = {}
    for niveau in Niveau.objects.order_by("id"):
        key = niveau.nom.casefold()
        if key not in niveaux:
            niveaux[key] = niveau
            continue
        canonical = niveaux[key]
        Sujet.objects.filter(niveau_id=niveau.id).update(niveau_id=canonical.id)
        Utilisateur.objects.filter(niveau_id=niveau.id).update(niveau_id=canonical.id)
        niveau.delete()

    matieres = {}
    for matiere in Matiere.objects.order_by("id"):
        key = (matiere.filiere_id, matiere.nom.casefold())
        if key not in matieres:
            matieres[key] = matiere
            continue
        canonical = matieres[key]
        Sujet.objects.filter(matiere_id=matiere.id).update(matiere_id=canonical.id)
        matiere.delete()

    subscriptions = set()
    for subscription in PushSubscription.objects.order_by("id"):
        key = (subscription.utilisateur_id, subscription.endpoint)
        if key in subscriptions:
            subscription.delete()
        else:
            subscriptions.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_verification_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sujet",
            name="fichier_pdf",
            field=models.FileField(
                upload_to="sujets/", validators=[core.utils.valider_pdf_upload]
            ),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="telechargements",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="vues",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="activite",
            index=models.Index(
                fields=["utilisateur", "-cree_le"], name="activite_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presencesession",
            index=models.Index(
                fields=["utilisateur", "-debut"], name="presence_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sujet",
            index=models.Index(
                fields=["statut", "visibilite", "-date_publication"],
                name="sujet_catalog_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sujet",
            index=models.Index(
                fields=["filiere", "annee_academique"], name="sujet_filiere_annee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sujet",
            index=models.Index(fields=["-vues"], name="sujet_vues_idx"),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(
                fields=["email", "usage", "utilise", "-expire_le"],
                name="verification_lookup_idx",
            ),
        ),
        migrations.RunPython(deduplicate_catalog_and_push, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="matiere",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nom"),
                models.F("filiere"),
                name="uniq_matiere_nom_filiere_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="niveau",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nom"), name="uniq_niveau_nom_ci"
            ),
        ),
        migrations.AddConstraint(
            model_name="pushsubscription",
            constraint=models.UniqueConstraint(
                fields=("utilisateur", "endpoint"), name="uniq_push_user_endpoint"
            ),
        ),
    ]
